# Generated by Django 6.0.6 on 2026-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
